### PR TITLE
Fix SaveAwareArgResolver ignored in nested mutations

### PR DESCRIPTION
**Pull request by spawnia**
Fixes a regression from https://github.com/nuwave/lighthouse/pull/2777 (v6.68.0) where `SaveAwareArgResolver::runBeforeSave()` was only honoured at the top level of a mutation. One level down inside nested HasMany/HasOne/ManyToMany/BelongsTo mutations, the pre-save resolver ran AFTER the child model was already persisted — silently discarding its attribute changes.

The root cause: `ResolveNested` defaulted to a partitioner that unconditionally routed all resolver-bearing args into the post-save set. Only `ModelMutationDirective::executeMutation()` overrode this with the pre-save-aware variant; all 12 nested resolver call sites used the broken default.

The fix collapses `nestedArgResolversWithoutPreSave` into `nestedArgResolvers` so the correct behavior is the default everywhere. When root is not a Model, behavior is unchanged. When root is a Model, `SaveAwareArgResolver` instances with `runBeforeSave=true` stay in the regular set so `SaveModel` executes them before persisting. The now-redundant explicit partitioner in `ModelMutationDirective` is removed.

Coverage spans the `create`, `update` and `upsert` branches of nested relation mutations, since all three build `ResolveNested` with the same default partitioner. Each new test fails without the fix, leaving the attributes null.

## Second fix: silent data loss when a `@nest` child collides with a sibling

Making `nestedArgResolvers` the default widened the reach of a separate, pre-existing bug (from https://github.com/nuwave/lighthouse/pull/2764, v6.68.0): lifting pre-save resolvers out of `@nest` wrote them into the flat regular set keyed by the child's bare field name. Field names are unique per input type, not across an input tree, so a name coincidence silently discarded an argument. Three ways to lose data:

1. A plain sibling `difficulty: Int` next to a `@nest` child `difficulty: LocationInput @geocode` — different columns, no semantic conflict, yet `difficulty` persisted as null.
2. Same-named children of two sibling `@nest` blocks — one resolver silently never ran.
3. A `@nest` child named `id` clobbering the primary key that `UpdateModel` and `UpsertModel` consume to identify the row.

Widening the default also turned case 3 into a hard error where the colliding name matched a relation operation namespace (`create`/`update`/…), since `NestedOneToMany` and friends then iterate an `ArgumentSet` where they expect a list.

Resolvers are not name-addressed — `SaveModel` iterates them by value and discards the keys — so lifted resolvers now travel as an ordered list rather than a name-keyed map, handed to the saver through the new `PreSaveArgumentsAware` interface. Lifting also no longer mutates the nest it reads from, which matters because `FieldValue` caches transformed argument sets per path and `@spread` shares `Argument` objects across rebuilt sets.

The capability check is what keeps this non-regressive: `UpdateModel` and `UpsertModel` forward it to their own `previous` (via the shared `DelegatesPreSaveArguments` trait), and a saver that can not consume the list gets nothing lifted, so its children run post-save exactly as on master. Both declining paths are covered by unit tests: a `previous` that does not implement the interface, and one that implements it but returns `null`. Third-party savers built as `new ResolveNested($closure)` — the pattern documented in `docs/master/concepts/arg-resolvers.md` — fall into the first case.

All colliding resolvers now run in schema order, so the last write wins where two of them target the same column. The interface is deliberately not marked `@api`.

Still open, and out of scope here: `@nest` inside a relation operation namespace has its lifted pre-save resolvers ignored entirely, because `NestedOneToMany` and friends never consume them. The hard error is gone; whether `@nest` should be legal there at all is a separate design question.

One unrelated commit names the `strict` flag on the existing `in_array()` calls in `src/`, which is purely cosmetic and easy to drop if you would rather keep it out.

🤖 Generated with Claude Code

### CODE REVIEW

**Comment by spawnia** [comment]
Self-reviewed at 18882fb6 (thorough, full)

🤖 Posted by Claude Code

**Comment by spawnia** [comment]
Self-reviewed at 89a56a2 (standard, full)

🤖 Posted by Claude Code
